

def make_promt(text:str ="hhh") -> str:
    """ 将文本转换为模型的提示词格式
    Args:
        text (str): 输入的文本内容
    Returns:
        str: 格式化后的提示词
    """
    promt = " Analyze the following text and determine if it was generated by a human or AI."
    return promt

def map_function(example):
    """ 将每个样本转换为模型的输入格式
    Args:
        example (dict): 输入样本
    Returns:
        dict: 转换后的样本
    """
    text = example["text"]
    label = example["label"]
    prompt = make_promt(text)
    
    return {
        "instruction": prompt,
        "input": text,
        "output": "AI" if label == 1 else "Human"
    }